// <auto-generated />
using Demo01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200623042201_SeedingEmployeeData")]
    partial class SeedingEmployeeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo01.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarPath");

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "./images/anh trung.jpg",
                            Department = 0,
                            Email = "trung@gmail.com",
                            FullName = "Trung Nguyen"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "./images/quang.jpg",
                            Department = 1,
                            Email = "Quang@gmail.com",
                            FullName = "Quang Nguyễn"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "./images/trâm.png",
                            Department = 3,
                            Email = "tram@gmail.com",
                            FullName = "Trâm Nguyễn"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "./images/minh.jpg",
                            Department = 2,
                            Email = "minh@gmail.com",
                            FullName = "Minh Nguyễn"
                        },
                        new
                        {
                            Id = 5,
                            AvatarPath = "./images/chị ghi.jpg",
                            Department = 3,
                            Email = "ghi@gmail.com",
                            FullName = "Ghi Nguyễn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
